name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - uses: actions/setup-node@v1
        with:
          node-version: 12.14.0

      - name: Install dependencies
        run: npm ci

      - name: Test ESLint
        run: npm run test:eslint

      - name: Test Stylelint
        run: npm run test:stylelint

      - name: Test Markdown
        run: npm run test:markdown

      - name: Build
        run: |
          npm run build
          npm run build:examples
          npm run docs:build

      - name: Upload docs artifacts
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs/site

      - name: Upload demo artifacts
        uses: actions/upload-artifact@v1
        with:
          name: demo
          path: examples

  deploy-gh-pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download docs artifacts
        uses: actions/download-artifact@v1
        with:
          name: docs

      - name: Deploy to Github Pages
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  deploy-netlify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download demo artifacts
        uses: actions/download-artifact@v1
        with:
          name: demo

      - uses: actions/setup-node@v1
        with:
          node-version: 12.14.0

      - name: Install dependencies
        run: npm i -g netlify-cli

      - name: Deploy to Netlify
        run: |
          npm i -g netlify-cli
          netlify deploy --site ${{ secrets.NETLIFY_APP_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
