name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.14.0

      - name: Install dependencies
        run: npm ci

      - name: Test ESLint
        run: npm run test:eslint

      - name: Test Stylelint
        run: npm run test:stylelint

      - name: Test Markdown
        run: npm run test:markdown

      - name: Build
        run: |
          npm run build
          npm run build:example
          npm run docs:build

      - name: Deploy to Netlify
        run: |
          mv examples/demo/ docs/site/demo/
          mv examples/dist/ docs/site/dist/
          npm i -g netlify-cli
          netlify deploy --site ${{ secrets.NETLIFY_APP_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
